### ISSUE TITLE
如果有注入CSS的话，Minify会失效

### ISSUE THREAD

**Issue by CHOYSEN** [vbenjs/vite-plugin-html#1]
比如在`examples/src/App.vue`里加入 CSS 样式再`vite build`，Vite 对于 CSS 的注入会晚于`pre`的钩子。

我建议把`template`和`minify`拆成两个插件导出，你觉得 OK 的话我可以发个 PR。

**Comment by anncwb** [comment]
原先vite的设计可以通知支持多个。我在看下有没有更好的方式

**Comment by anncwb** [comment]
2.0我正在正式  这几天会修复

**Comment by anncwb** [comment]
刚看了下  vite2.0支持导出多个数组。现在修复了 .可以升级到2.0.0-beta.3
