### ISSUE TITLE
Provide a default template?

### ISSUE THREAD

**Issue by theoephraim** [vbenjs/vite-plugin-html#10]
In the past when using https://github.com/jantimon/html-webpack-plugin I would normally not have an index.html file defined at all and just rely on the plugin to create it for me. This meant the only interesting thing about the template at all is the path to my js entrypoint.

Would you be open to adding some functionality like this that provides a very basic default template if none is defined?

**Comment by anncwb** [comment]
Maybe you can upgrade to 3.0.0, and reconfigure your project
