### ISSUE TITLE
Include ejs file with parameters

### ISSUE THREAD

**Issue by pierredarrieutort** [vbenjs/vite-plugin-html#12]
I've setup a new Vite project (as vanilla JS project)

Two questions :
 - How can we include a sub-file like a `header.ejs` (renamed as .html because .ejs isn't recognized by your plugin like for `index.html`) ?
 - Is it possible to pass variables in this included file ?

**Comment by anncwb** [comment]
Currently this function is not supported, only ejs template syntax is supported
