### ISSUE TITLE
can i output html to disk when i use dev server

### ISSUE THREAD

**Issue by u373693041** [vbenjs/vite-plugin-html#13]
just lisk alwaysWriteToDisk in htmlWebpackPlugin

**Comment by anncwb** [comment]
The html of vite itself is on the disk, what do you need?

**Comment by u373693041** [comment]
my web server is provided by php, 
so i want to output the html which is compiled by the plugin to the php project when i use dev server,
can i use the plugin to finish it?
thank you

**Comment by u373693041** [comment]
> The html of vite itself is on the disk, what do you need?

my web server is provided by php,
so i want to output the html which is compiled by the plugin to the php project when i use dev server,
can i use the plugin to finish it?
thank you
