### ISSUE TITLE
Deprecation messages in Vite 5

### ISSUE THREAD

**Issue by marvinruder** [vbenjs/vite-plugin-html#134]
After upgrading to Vite 5, I see the following warning messages when starting the Vite server or building with Vite:

```
 WARN  plugin 'vite:html' uses deprecated 'enforce' option. Use 'order' option instead.
 WARN  plugin 'vite:html' uses deprecated 'transform' option. Use 'handler' option instead.
```

**Comment by changweihua** [comment]
any plan to publish to npmjs.com ?

**Comment by wen403** [comment]
什么时候更新啊

**Comment by wojtekmaj** [comment]
Try [vite-plugin-simple-html](https://www.npmjs.com/package/vite-plugin-simple-html).
It doesn't have as many features, but doesn't produce this warning. You can consider it a "lite" version of this plugin, but maybe it will cover your needs (it covers mine!).

**Comment by webJose** [comment]
I just tried `vite-plugin-simple-html`.  It is merely a variable replacer that looks for variables with a regular expression.  It doesn't really execute EJS.

**Comment by marvinruder** [comment]
Unfortunately, this issue (#134) is not solved by #137. The deprecation messages still show up in the build output with plugin version v3.2.1.

**Comment by marvinruder** [comment]
The issue is solved for me now when adding `viteNext: true` to the plugin options. Thanks for the fix!

A future implementation might even be able to read the installed version of Vite and behave accordingly without the need for an explicit option (especially since future breaking changes in Vite 6+ may require an additional option `viteNextNext` or similar), but for now my problem is gone.

**Comment by ryomahan** [comment]
> A future implementation might even be able to read the installed version of Vite and behave accordingly without the need for an explicit option (especially since future breaking changes in Vite 6+ may require an additional option `viteNextNext` or similar), but for now my problem is gone.

I tired to do this, but couldn't find a good way to get the version number of the vite currentily used by the external project(Maybe there are some ways to do it and I just didn't find it ).

**Comment by marvinruder** [comment]
> I tired to do this, but couldn't find a good way to get the version number of the vite currentily used by the external project(Maybe there are some ways to do it and I just didn't find it ).

At least the latest version of Vite appears to export its `version`, so `import { version } from "vite";` should do the trick.

There are some other ways to do this using Vite’s `package.json`, but they use Node.js APIs that are still experimental:

- `import.meta.resolve("vite/package.json")` returns the URL to Vite’s `package.json`, but uses `import.meta.resolve` with stability “1.2 - Release candidate” ([see more](https://nodejs.org/api/esm.html#importmetaresolvespecifier))
- `import vitePackageJson from "vite/package.json" assert { type: "json" };` stores Vite’s version in `vitePackageJson.version`, but uses JSON modules, which is at stability “1 - Experimental” ([see more](https://nodejs.org/api/esm.html#json-modules))

**Comment by haiweilian** [comment]
> At least the latest version of Vite appears to export its `version`, so `import { version } from "vite";` should do the trick.
> 
> There are some other ways to do this using Vite’s `package.json`, but they use Node.js APIs that are still experimental:
> 
> * `import.meta.resolve("vite/package.json")` returns the URL to Vite’s `package.json`, but uses `import.meta.resolve` with stability “1.2 - Release candidate” ([see more](https://nodejs.org/api/esm.html#importmetaresolvespecifier))
> * `import vitePackageJson from "vite/package.json" assert { type: "json" };` stores Vite’s version in `vitePackageJson.version`, but uses JSON modules, which is at stability “1 - Experimental” ([see more](https://nodejs.org/api/esm.html#json-modules))

When 'vite>2' the 'version' constant can be used.  I don't want to configure 'ViteNext'.

**Comment by ryomahan** [comment]
> When `vite>2` the `version` constant can be used. I don't want to configure `ViteNext`. I think [#135 (comment)](https://github.com/vbenjs/vite-plugin-html/pull/135#issuecomment-1842548567)
`version` can't be used in vite v2.x, it has been defined since v3.0，But this package needs to support vite version >=2.0.0, so we can't use this way.

**Comment by marvinruder** [comment]
> > When `vite>2` the `version` constant can be used. I don't want to configure `ViteNext`. I think [#135 (comment)](https://github.com/vbenjs/vite-plugin-html/pull/135#issuecomment-1842548567)
> 
> `version` can't be used in vite v2.x, it has been defined since v3.0，But this package needs to support vite version >=2.0.0, so we can't use this way.

But we can catch this. How about

```javascript
async function getViteMajorVersion() {
  try {
    let { version } = await import("vite");
    return Number(version.split(".")[0]);
  } catch (_) {
    return 2;
  }
}
```

**Comment by ryomahan** [comment]
> But we can catch this. How about

Yeah! I just thought of that too, I'm coding now.

**Comment by ryomahan** [comment]
There is a new question, do I need to keep the `viteNext`.  @marvinruder

**Comment by marvinruder** [comment]
> There is a new question, do I need to keep the `viteNext`. @marvinruder

@ryomahan I believe we can remove it. Even in the future, we should be able to adapt to the different behavior of major Vite versions using the function I proposed. Also, for users it is difficult to understand which versions of Vite are `next`.

**Comment by ryomahan** [comment]
> @ryomahan I believe we can remove it. Even in the future, we should be able to adapt to the different behavior of major Vite versions using the function I proposed. Also, for users it is difficult to understand which versions of Vite are `next`.

My concern is whether this will affect people who have already upgraded vite-plugin-html.

**Comment by marvinruder** [comment]
> > @ryomahan I believe we can remove it. Even in the future, we should be able to adapt to the different behavior of major Vite versions using the function I proposed. Also, for users it is difficult to understand which versions of Vite are `next`.
> 
> My concern is whether this will affect people who have already upgraded vite-plugin-html.

There should be no troubles in JavaScript, additional entries in the user options object are probably ignored.

For TypeScript, we could keep the option in https://github.com/vbenjs/vite-plugin-html/blob/ad22da1b7468d286599228b4bf001aa93bc4d53f/packages/core/src/typing.ts#L65 and mark it as deprecated in JSDoc:

```javascript
    /**
     * fit vite2+
     * 
     * @deprecated This option is no longer needed and can be safely removed from your configuration, as the plugin will
     *             automatically detect the version of Vite from now. This option will be removed in the next major
     *             version.
     */
    viteNext?: boolean;
```

But I am also fine with removing it entirely, the very few users of this option (which has been published for a very short time) are probably also reading this discussion.

**Comment by ryomahan** [comment]
Ok, I'll submit the PR after verifying that the code is ok.

**Comment by ryomahan** [comment]
> Ok, I'll submit the PR after verifying that the code is ok.

Another tricky question, the createPlugin method is not async...

**Comment by marvinruder** [comment]
> Another tricky question, the createPlugin method is not async...

I made it `async` and tested it, everything seemed working fine. Vite accepts `async` plugins (see https://github.com/vitejs/vite/discussions/8509, https://github.com/vitejs/vite/pull/8574)

**Comment by ryomahan** [comment]
> Edit: It accepts `async` plugins starting with version 3 – this may be a problem. In this case, we can switch from
> 
> ```js
> import { … } from "vite";
> ```
> 
> to
> 
> ```js
> import vite from "vite";
> ```
> 
> or
> 
> ```js
> import * as vite from "vite";
> ```
> 
> and check whether `vite.version` is defined or not (and use `vite.…` in other places of the module).

That's a good idea, I've spent a lot of time on how to handle asynchronous results.

**Comment by ryomahan** [comment]
finish it in  #140

**Comment by zkvvv** [comment]
> After upgrading to Vite 5, I see the following warning messages when starting the Vite server or building with Vite:
> 
> ```
>  WARN  plugin 'vite:html' uses deprecated 'enforce' option. Use 'order' option instead.
>  WARN  plugin 'vite:html' uses deprecated 'transform' option. Use 'handler' option instead.
> ```

/**
       * If you are using vite that version higher than 5.0.0-beta.13, you can set viteNext to true to align vite's config
       */
      viteNext: true,
