### ISSUE TITLE
vite5警告：使用了废弃语法

### ISSUE THREAD

**Issue by peerless-hero** [vbenjs/vite-plugin-html#141]
vite具体版本：5.0.11
vite打包警告：
```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

 WARN  plugin 'vite:html' uses deprecated 'enforce' option. Use 'order' option instead.                                                                            

 WARN  plugin 'vite:html' uses deprecated 'transform' option. Use 'handler' option instead.    
```
希望尽快适配以消除警告。

**Comment by cctvhe11** [comment]
升级 3.2.1，使用 viteNext: true配置，可以消除

**Comment by Ace627** [comment]
```
createHtmlPlugin({
  // 启用 Vite 最新语法模式
  viteNext: true,
  // 在这里写 entry 后，你将不需要在 `index.html` 内添加 script 标签，原有标签需要删除
  entry: 'src/main.ts',
  // 是否压缩 html
  minify: true,
  // 需要注入 index.html ejs 模版的数据
  inject: {
    data: { title: '动态标题', buildTime: new Date().toLocaleString() },
  },
})
```

**Comment by qeleb** [comment]
@peerless-hero The issue you are describing still exists in the latest release 3.2.1, but it was already fixed & merged to the main branch a few days ago. A release is on the way in the coming days.

@cctvhe11 @Ace627, the `viteNext` property has been removed, so when the next release is out, you may remove it from your configuration

**Comment by peerless-hero** [comment]
@qeleb 感谢你的及时跟进。
Thank you for your timely follow-up.

**Comment by mark-hahn** [comment]
@qeleb: I have a stupid question.  You say to use release 3.2.2 but my npm update only takes it to ` vite-plugin-html@2.1.1`.  And the tags in this repo only go to 3.07.  What am I missing?  How do I get 3.2.2?

**Comment by mark-hahn** [comment]
Never mind.  My package.json, which was installed by vite create, had the version 2.1.1 hardwired.  Also, I thought npm update always went to latest version and also changed package.json.  I told you it was a stupid question.

**Comment by mark-hahn** [comment]
AARGH.  Updating to 3.2.2 blew things up.  I'm now getting ...
```
 failed to load config from C:\Users\mark\apps\tv-series-client\vite.config.js

 ERROR  error when starting dev server: 
TypeError: (0 , import_vite_plugin_html.injectHtml) is not a function
```

Can you please help me out here?

**Comment by mark-hahn** [comment]
sorry for all the posts
My vite.config is ...
```
import { defineConfig } from 'vite';
import path from 'path';
import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import envCompatible from 'vite-plugin-env-compatible';
import { injectHtml } from 'vite-plugin-html';
import { viteCommonjs } from '@originjs/vite-plugin-commonjs';

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: [
      {
        find: /^~/,
        replacement: ''
      },
      {
        find: '@',
        replacement: path.resolve(__dirname, 'src')
      }
    ],
    extensions: [
      '.mjs',
      '.js',
      '.ts',
      '.jsx',
      '.tsx',
      '.json',
      '.vue'
    ]
  },
  plugins: [
    vue(),
    vueJsx(),
    viteCommonjs(),
    envCompatible(),
    injectHtml()
  ],
  server: {
    strictPort: false,
  },
  build: {
    outDir: "shows",
  }
})

```

**Comment by mark-hahn** [comment]
Removing the two lines containing `injectHtml ` fixed my problem.  All these posts show that I should work harder on my problems before posting.  Sorry.
