### ISSUE TITLE
Multiple entry points

### ISSUE THREAD

**Issue by fatso83** [vbenjs/vite-plugin-html#16]
Hi, it seems this plugin only accepts a single options object, but I need to pass a different set of options (fields) to different templates, as I have multiple entry points (html files) that need to be processed. How would I do that, if possible at all?

**Comment by unknownzjc** [comment]
这个功能目前我也有需求，不知道 @anncwb 那边有木有时间做这一块的内容呢？如果没有的话，我可以贡献一下PR

**Comment by anncwb** [comment]
3.0.0 has made major changes and can be upgraded to 3.0.0, which already supports multi-page applications
