### ISSUE TITLE
关于重构

### ISSUE THREAD

**Issue by CHOYSEN** [vbenjs/vite-plugin-html#2]
Hello，我是上次在 vite-plugin-html 里面提 issue 的，我看到你的修复了，但我还是觉得应该重构，原因主要有下面几点：

1、用户可能只需要 minify 或者 template 这两个功能中的其一，但目前的方式是默认导出两个 plugin，Vite 会把这两个 plugin 都放到 rollup 里面，这在大型项目里面可能是个性能负担。我认为可以重构成导出两个函数，用户按需引入就好。
2、目前提供的`tags`和`viteHtmlPluginOptions`实际上是一种功能，我认为有点类似 Vue 模板和 h 函数的关系。为了避免心智负担，保留最简单的用法也就是模板即可。
3、模板功能目前使用的是`lodash`，我认为`ejs`提供的功能更强大而且更轻量（1.4M size + 12W dependents vs 134K size + 8K dependents）。

我目前基本重构好了，如果你觉得OK我可以发PR。
# breaking change
```js
// vite.config.ts
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';

import { minifyHtml, injectHtml } from '../src/index';

export default defineConfig({
  plugins: [
    vue(),
    minifyHtml(),
    injectHtml({
      title: 'vite-plugin-html-example',
      injectScript: '<script src="./inject.js"></script>'
    })
  ]
})
```

```html
// index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <link rel="icon" href="/favicon.ico" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>
    <%= title %>
  </title>
</head>

<body>
  <div id="app"></div>
  <%- injectScript %>
  <script type="module" src="/src/main.ts"></script>
</body>

</html>
```

**Comment by anncwb** [comment]
你提上来

**Comment by anncwb** [comment]
其实模版值对于html 对性能可以忽略

**Comment by anncwb** [comment]
关于tag和options,其实这是插件需要提供的。让用户去选择，喜欢自定义的可以选择options，不喜欢直接在html内改的。可以选择tag

**Comment by CHOYSEN** [comment]
> 其实模版只针对html 性能可以忽略。不是写在transform内都还好。我也是参考webpack-html选择的lodash。你提上来我再看看

我又去重新看了一下，确实针对html的性能是可以忽略的。

**Comment by anncwb** [comment]
ejs这个我可以接受。我会做下调整。我还是觉得需要整体导出。所以我export default的两个。但同时也兼容独立导出。关于tags，我觉得这是需要提供的。同时后续应该会在里面加上html骨架屏功能，这个也会独立出跟你写的那样。
