### ISSUE TITLE
`minify: false` 不生效

### ISSUE THREAD

**Issue by Junior2Ran** [vbenjs/vite-plugin-html#21]
👴🏻配置了minify:false然而index.html依然会压缩成一行，拜读源码后发现minifyHtml里似乎只判断了是否为boolean，但是没有判断是否为true或false，从而导致minify一定会执行
不知👴🏻的猜测是否有迹可循，如果不对，还烦请指正

**Comment by anncwb** [comment]
3.0.0 做了比较大的改动，可以升级到3.0解决
