### ISSUE TITLE
TypeError: (0 , import_vite_plugin_html.default) is not a function

### ISSUE THREAD

**Issue by DoubleRayWang** [vbenjs/vite-plugin-html#27]
升级后报错

TypeError: (0 , import_vite_plugin_html.default) is not a function

**Comment by DoubleRayWang** [comment]
**原来是导出方式变了~~**

import createHtmlPlugin from 'vite-plugin-html'
改为
import { createHtmlPlugin } from 'vite-plugin-html'

**Comment by mxp131011** [comment]
> **原来是导出方式变了~~**
> 
> import createHtmlPlugin from 'vite-plugin-html' 改为 import { createHtmlPlugin } from 'vite-plugin-html'

3.0.3还是有点问题,在路由重定向时会报错，

**Comment by DoubleRayWang** [comment]
> > **原来是导出方式变了~~**
> > import createHtmlPlugin from 'vite-plugin-html' 改为 import { createHtmlPlugin } from 'vite-plugin-html'
> 
> 3.0.3还是有点问题,在路由重定向时会报错，

这个插件和路由没啥关系吧

**Comment by mxp131011** [comment]
> > > **原来是导出方式变了~~**
> > > import createHtmlPlugin from 'vite-plugin-html' 改为 import { createHtmlPlugin } from 'vite-plugin-html'
> > 
> > 
> > 3.0.3还是有点问题,在路由重定向时会报错，
> 
> 这个插件和路由没啥关系吧

升级到3.0.3后平时用没问题，但是比如访问一个不存在的路由，被重定向404页面时就会报错

**Comment by anncwb** [comment]
> > > > **原来是导出方式变了~~**
> > > > import createHtmlPlugin from 'vite-plugin-html' 改为 import { createHtmlPlugin } from 'vite-plugin-html'
> > > 
> > > 
> > > 3.0.3还是有点问题,在路由重定向时会报错，
> > 
> > 
> > 这个插件和路由没啥关系吧
> 
> 升级到3.0.3后平时用没问题，但是比如访问一个不存在的路由，被重定向404页面时就会报错

你有配置vue-router吗，我没复现，可以给我一个示例？
