### ISSUE TITLE
3.0.3还是有点问题，请看Demo

### ISSUE THREAD

**Issue by mxp131011** [vbenjs/vite-plugin-html#28]
# The latest version (3.0.3) reported an error: [Demo](https://github.com/mxp131011/test)

![image](https://user-images.githubusercontent.com/31055355/151476122-7b2d8d9f-a216-48ff-94d2-b5079f4f1dde.png)

**Comment by mxp131011** [comment]
虽然不是最小示例，但可以检测问题了

**Comment by mxp131011** [comment]
路由拦截在`src\router\router-guard.js`

**Comment by mxp131011** [comment]
更新了一下仓库，精简了路由拦截

**Comment by DoubleRayWang** [comment]
遇到了同样的问题

**Comment by rogyvoje** [comment]
Got the same error with the new version. Figured out it happens only in dev mode, build works fine.

**Comment by bodograumann** [comment]
Something similar happens to me in dev mode. I have the following in index.html:
```
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
```
It is not replaced anymore in v3. Event explicitely adding `inject: { data: { BASE_URL: "…" } }` does not help.

**Comment by vlechemin** [comment]
It seems to be related to this:

From `defineConfig` `plugins` documentation.
>  * By default, the plugins are run during both serve and build. When a plugin
>  * is applied during serve, it will only run **non output plugin hooks** (see
>  * rollup type definition of {@link rollup#PluginHooks}). You can think of the
>  * dev server as only running `const bundle = rollup.rollup()` but never calling
>  * `bundle.generate()`.

And it seems `generateBundle` appears in `OutputPluginHooks` from rollup.

I hope it helps

**Comment by anncwb** [comment]
try 3.0.5
