### ISSUE TITLE
执行 pnpm add -D vite-plugin-html 时报错

### ISSUE THREAD

**Issue by DoubleRayWang** [vbenjs/vite-plugin-html#29]
WARN  Package name mismatch found while reading {"integrity":"sha512-z7O0IS8Plc39rTCq6i6iHxk43duYOn8uFJiWSewIq0Bww1RNybVHSCjahmcC87ZqAm4OTvFzlzeGu3XAzG1ctQ==","registry":"https://registry.npmjs.org/","tarball":"https://registry.npmjs.org//filelist/-/FileList-1.0.2.tgz"} from the store. This means that the lockfile is broken. Expected package: FileList@1.0.2. Actual package in the store by the given integrity: filelist@1.0.2.

**Comment by DoubleRayWang** [comment]
看报错的意思应该是FileList这个包的问题

**Comment by Jungzl** [comment]
我遇到了同样的问题，在我把.pnpm-store 删掉重新安装后没有出现了
