### ISSUE TITLE
3.0.4有问题，对于注入script标签方式在vue项目中开发时无法运行，会提示报错语法错误

### ISSUE THREAD

**Issue by zxiaozhou** [vbenjs/vite-plugin-html#30]
1. 错误截图
<img width="740" alt="image" src="https://user-images.githubusercontent.com/62740686/153036133-dac40d91-8ff2-4ee9-897d-3c5d77b27b07.png">

2. vue中html代码
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%- title %></title>
  </head>
  <body>
    <div id="app"></div>
    <%- injectScript %>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>

```
3. 去掉‘ <%- injectScript %>’后正常，即：<%- title %>能正常渲染
4. 个人觉得编译后<%- injectScript %>会生成对于的代码，，但是vite开发时无法生成，不知道为啥3.0没有了tag的支持(或者有能否提供下案例)

**Comment by DoubleRayWang** [comment]
injectScript是自己配置的key，仔细看文档~

**Comment by zxiaozhou** [comment]
@DoubleRayWang 我知道是自己配置的key,不就是这个吗(打包编译没问题，，有问题的是开发npm run dev会报错)
<img width="660" alt="image" src="https://user-images.githubusercontent.com/62740686/153115026-7efacf6e-fff6-4aa7-b3aa-412a113d92a0.png">

**Comment by anncwb** [comment]
尝试3.0.5，我这边没有复现，还是不行可以提供一个最小的复现示例给我下

**Comment by zxiaozhou** [comment]
我晚上上传一个最小案例



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月09日 16:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [vbenjs/vite-plugin-html] 3.0.4有问题，对于注入script标签方式在vue项目中开发时无法运行，会提示报错语法错误 (Issue #30) |

尝试3.0.5，我这边没有复现，还是不行可以提供一个最小的复现示例给我下

**Comment by zxiaozhou** [comment]
@DoubleRayWang 最小案例地址：https://github.com/zxiaozhou/example，运行后截图：
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/62740686/153163282-edf71eb2-2fcd-406f-825f-b58f656477f3.png">

**Comment by anncwb** [comment]
排查一下为什么你会有这种请求，这个请求造成的 
<img width="884" alt="image" src="https://user-images.githubusercontent.com/28132598/153323513-7abff4b7-8933-45cb-a05b-d0f5b9aa9455.png">

**Comment by optim-zhang-zhoujie** [comment]
@zxiaozhou 
我也是从naive-ui-admin过来的，换成`injectScript`的写法没问题。

**Comment by uruz-7** [comment]
@zxiaozhou 
我也是从naive-ui-admin过来的，换成`injectScript`的写法没问题。

**Comment by uruz-7** [comment]
@anncwb 
我这里虽然不报错但是会出一个warning，因为操作是一样的就不新开一个issue了。

我也是改成这种写法
```js
data: {
    title:"title",
    injectScript: <script src="1.js"></script>,
},
```
然后用vite build以后除了会出这样的warning以外，运行一切正常
` WARN  <script src="/1.js"> in "/index.html" can't be bundled without type="module" attribute`
查了下原因是vite会以为你要把资源打包进去，但是实际上并不需要
https://stackoverflow.com/questions/70951072/vite-build-warns-script-cant-be-bundled-without-type-module-attribute

**Comment by zxiaozhou** [comment]
@anncwb 确实是哪个请求造成的，如果 @uruz-7 不需要处理我就关了issue吧
