### ISSUE TITLE
按照demo配置后，运行失败，提示          html = await server.transformIndexHtml?.(url, html, req.originalUrl); 异常

### ISSUE THREAD

**Issue by BruceLee316** [vbenjs/vite-plugin-html#32]
目前安装的vite-plugin-html版本3.0.5

![2A26D28A-9366-4e11-A555-407F1D7CE804](https://user-images.githubusercontent.com/34764315/153325289-6ec4760b-75e5-423a-a559-613e4cab847a.png)
![E6168526-AE58-45a8-9154-F5C3279EC308](https://user-images.githubusercontent.com/34764315/153325318-df55ce5d-ae61-4466-b7f6-4017b47ae408.png)

**Comment by anncwb** [comment]
可以看你的 tsconfig.json怎么配置的，或者提供一下demo给我

**Comment by gpampara** [comment]
Version of nodejs should be >= 14 to have this work without transformations

**Comment by BruceLee316** [comment]
这是demo，麻烦了
[vite.zip](https://github.com/vbenjs/vite-plugin-html/files/8039659/vite.zip)

**Comment by BruceLee316** [comment]
> 可以看你的 tsconfig.json怎么配置的，或者提供一下demo给我

这是demo 麻烦了，我的node版本是12.18.4
[vite.zip](https://github.com/vbenjs/vite-plugin-html/files/8039659/vite.zip)
