### ISSUE TITLE
Changelog doesn't communicate breaking changes

### ISSUE THREAD

**Issue by idleberg** [vbenjs/vite-plugin-html#42]
It would be helpful for users of this package, if the changelog would be complete. 

![image](https://user-images.githubusercontent.com/1504938/155700496-7261a610-973c-4c96-bbae-9e870cd0fa82.png)

As you can see, it's unclear which breaking changes caused the bump from 2.x to 3.x. What's the point of keeping a changelog, if it's (apparently) incomplete and people end up going through single commits to see what has changed?

**Comment by anncwb** [comment]
Sorry for the negligence, will pay attention next time
