### ISSUE TITLE
vite2中，首次安装库，在 html 写入 <%- injectScript %> 后，加载文件会出现 408 连接超时

### ISSUE THREAD

**Issue by Greasen** [vbenjs/vite-plugin-html#43]
vite2中，首次安装库，在 html 写入 <%- injectScript %> 后，加载文件会出现 408 连接超时，是因为什么呢？注释掉后，不会出现 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="icon" href="/favicon.ico" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= title %></title>
  <script src="./config/api.config.js"></script>
</head>

<body>
  <div id="app"></div>
  <script type="module" src="/src/main.ts"></script>
</body>

</html>

希望：
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="icon" href="/favicon.ico" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= title %></title>
  <%- injectScript %>
</head>

<body>
  <div id="app"></div>
</body>

</html>

createHtmlPlugin({
    minify: true,
    entry: '/src/main.ts',
    inject: {
      // Inject data into ejs template
      data: {
        title: VITE_SYSTEM_NAME,
        injectScript: `<script src="./config/api.config.js"></script>`
      },
    },
  })

**Comment by anncwb** [comment]
can you give me a reproduction？

**Comment by Greasen** [comment]
不好意思，请忽略这个问题，是我在开发环境中运行的时候，没有进行预构建，导致 dependencies 会一直在更新；
